import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { QueryProvider } from "~/components/query/QueryProvider";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Toaster } from "~/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geist.variable}`}>
        <QueryProvider>
          <body className="dark">
            {children}
            <Toaster />
          </body>
        </QueryProvider>
      </html>
    </ClerkProvider>
  );
}
